insert into
 	activity_swap_biodata (
		data_source_id
		,data_source
		,station_id
		,site_id
		,event_date
		,activity
		,sample_media
		,organization
		,site_type
		,huc
		,governmental_unit_code
		,geom
		,organization_name
		,activity_id
		,activity_type_code
		,activity_start_time
		,act_start_time_zone
		,project_id
		,activity_comment
		,assemblage_sampled_name
		,act_reach_length
		,act_reach_length_unit
		,act_pass_count
		,sample_collect_method_id
		,sample_collect_method_ctx
		,sample_collect_method_name
		,act_sam_collect_meth_desc
		,sample_collect_equip_name
		,act_sam_collect_equip_comments
	)
	values (
		:dataSourceId
		,:dataSource
		,:stationId
		,:siteId
		,:eventDate
		,:activity
		,:sampleMedia
		,:organization
		,:siteType
		,:huc
		,:governmentalUnitCode
		,:geom
		,:organizationName
		,:activityId
		,:activityTypeCode
		,:activityStartTime
		,:actStartTimeZone
		,:projectId
		,:activityComment
		,:assemblageSampledName
		,:actReachLength
		,:actReachLengthUnit
		,:actPassCount
		,:sampleCollectMethodId
		,:sampleCollectMethodCtx
		,:sampleCollectMethodName
		,:actSamCollectMethDesc
		,:sampleCollectEquipName
		,:actSamCollectEquipComments
	)

